### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [42-tanaka/sagyo-no-otomo#35]
@42-tanaka 
お疲れ様です！

こちらMVPリリースレビューになります！

### 技術
MiniMagickを使って画像のサイズを整えていたり、保存先をS3にしていたりと画像を扱う上で大切な部分をしっかり押さえている印象を持ちました。

上記を踏まえて細かい点ですが、 以下FBとしてお伝えさせていただきます。

- ユーザー登録した後、他のユーザーが投稿のアイコンも自分にアイコンになってしまったり、編集、削除ができてしまうようですので、**ユーザーごとの画像の表示、current_userの値を使って、編集削除の出しわけ**をしてあげましょう。
- `app/controllers/posts_controller.rb`の`searchメソッド`の炉軸が少し複雑な印象ですので、**取得する値でscopeに切り出したり、privateに切り出して、そのメソッドを呼んであげる**等してあげると可読性が上がるかと思います。
- また、`scaffold`を使って作成したと思われるコメントアウトが残っているので、こちらも削除しておきましょう。

### ユーザビリティ
柔らかい印象のUIで整っていて、一覧ページなどが綺麗にできていると思いました。

上記を踏まえて細かい点ですが、 以下FBとしてお伝えさせていただきます。

- 絞り込み機能ですが、こちらはTOPページに表示してあげてもいいかなと思いました。（デザインが崩れる可能性があれば、トグル等のJSを書いてあげて、動的にだし分けられるようにしても良さそうです。）
- ハンバーガーメニューから遷移したページが基本的に右寄りに表示されているので、中心に寄せてあげましょう。
- Topページでの使い方説明ですが、**各項目を見ようとする際、「クリック」→ 「スクロール」→ 「クリック」と少しアクションが多い印象ですので、ここのアクションを減らせる**とユーザの負担が少なくなるかと思いました。

以上です！
柔らかい世界観かつ、画像の表示が綺麗にできているアプリケーションだと思いました！

LGTMです！

上記の内容を本リリース実装するタスクに組み込み、スケジュールを立ててみてください。

スケジュール決まりましたら共有をお願いできればと思います。

また上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by 42-tanaka** [comment]
MVPリリースレビューありがとうございます！
いただいたFBに関して、２点お聞きしたい点があります。

>絞り込み機能ですが、こちらはTOPページに表示してあげてもいいかなと思いました。（デザインが崩れる可能性があれば、トグル等のJSを書いてあげて、動的にだし分けられるようにしても良さそうです。）

こちらの「TOPページに表示」というのは、ログイン後に表示するTOPページに絞り込み機能を置き、検索条件を入れてフォームを送信すると絞り込み後の投稿一覧ページが開く、という理解であっていますでしょうか？
それとも、ヘッダーや投稿一覧ページの先頭に絞り込み機能を置く、ということでしょうか？
絞り込み検索のフォームが場所をとるため、トグル等での動的な出し分けは取り入れたいと思います！

>ハンバーガーメニューから遷移したページが基本的に右寄りに表示されているので、中心に寄せてあげましょう。

自分の環境（13インチMacbook、24インチモニター、8インチタブレット、5.8インチiphone）では、右寄りの状況が再現できませんでした。
レイアウトのズレの原因は画面サイズではないということでしょうか？
デバイスを変える他に確認方法があれば、ご教示いただきたいです。
また、お手数ですが、どのような表示になっているかスクリーンショットをいただけないでしょうか？

ご確認よろしくお願いいたします！

**Comment by tmtkzk0823** [comment]
> こちらの「TOPページに表示」というのは、ログイン後に表示するTOPページに絞り込み機能を置き、検索条件を入れてフォームを送信すると絞り込み後の投稿一覧ページが開く、という理解であっていますでしょうか？
それとも、ヘッダーや投稿一覧ページの先頭に絞り込み機能を置く、ということでしょうか？

混乱させて申し訳ありません🙇
「投稿一覧ページに表示する」が正しい表現です！
投稿一覧ページで検索をかけて、検索条件にヒットした投稿を表示してあげるようにしてあげるのが良さそうです！

> 自分の環境（13インチMacbook、24インチモニター、8インチタブレット、5.8インチiphone）では、右寄りの状況が再現できませんでした。

こちらも混乱させて申し訳ありません🙇
**左寄り**の間違いになります🙇‍♂️

**Comment by 42-tanaka** [comment]
@tmtkzk0823 

遅い時間までご対応いただいており、ありがとうございました🙇

>「投稿一覧ページに表示する」が正しい表現です！
投稿一覧ページで検索をかけて、検索条件にヒットした投稿を表示してあげるようにしてあげるのが良さそうです！

上記の内容で修正したいと思います。ありがとうございます！

>左寄りの間違いになります🙇‍♂️

もともと左寄りになってしまっていたものを、自分の環境や検証ページから中央に見えるように修正したつもりだったのですが、修正しきれていないようなので確認します！ありがとうございます🙇

本リリースは2/29を予定しています。
よろしくお願いいたします！
